# Generated by Django 2.1.2 on 2018-10-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isFavourite',
            field=models.BooleanField(default=False),
        ),
    ]
