# Generated by Django 2.1.2 on 2018-11-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_isfavourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumImage',
            field=models.FileField(upload_to=''),
        ),
    ]
